#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"
# sudo apt-get update
# sudo apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# echo 'Hello World!' > /var/www/html/index.html
# service nginx restart
# server {
#     listen 80;

#     location / {
#         add_header Content-Type text/html;

#         return 200 'Hello World!';
#     }
# }